// ============================================================================
//  woke.wtf — src/jvm/mappings.h
//
//  Loader for mappings.json (repo root): the curated Yarn→Intermediary
//  translation table for Minecraft 1.21.11, generated by
//  scripts/gen_mappings.py from yarn 1.21.11+build.6.
//
//  The loader auto-detects the schema: it accepts the current curated format
//  (meta + classes → { intermediary, fields, methods }) and falls back to a
//  flat { "<key>": { "class": …, "fields": …, "methods": … } } object or a
//  plain array of entries, so future regenerations stay loadable.
//
//  All parsed strings live in persistent storage for the process lifetime —
//  member lookups return stable pointers, never copies. Parsed once at init;
//  lookups are allocation-free hash hits afterwards.
// ============================================================================

#pragma once

#include <cstddef>

namespace woke::jvm::mappings {

/// One resolved class member (field or method) from mappings.json.
struct MemberInfo {
    const char *intermediary;  // e.g. "method_1551" / "field_1724"
    const char *sig;           // intermediary-space descriptor/signature
};

/// One curated class entry.
struct ClassInfo {
    const char *intermediary;  // e.g. "net/minecraft/class_310"
};

/// Parse `path` (default: "mappings.json" next to the process CWD).
/// Returns false when the file is missing, unparsable, or lacks class data.
/// Idempotent: a successful load makes later calls no-ops.
bool load(const char *path = "mappings.json");

/// Whether a mapping table is loaded and non-empty.
bool loaded();

/// Total curated class count (for diagnostics).
size_t class_count();

/// Look up a curated class by its symbolic key ("minecraft_client", …).
/// Returns nullptr when the key is unknown or mappings are not loaded.
const ClassInfo *find_class(const char *class_key);

/// Look up a curated field. Returns nullptr when unknown.
const MemberInfo *find_field(const char *class_key, const char *member_key);

/// Look up a curated method. Returns nullptr when unknown.
const MemberInfo *find_method(const char *class_key, const char *member_key);

/// Release all parsed data (library unload path).
void unload();

} // namespace woke::jvm::mappings
